---
deployment:
  tasks:
    - export DEPLOYPATH=../../public_html/
    - /bin/cp -f backend-gedure/* ../../laravel
    - /bin/rm -Rf ../../public_html/static
    - /bin/cp -f backend-gedure/public/* $DEPLOYPATH
    - cd ../../laravel
    - composer install
