---
deployment:
  tasks:
    - export DEPLOYPATH=../../public_html/
    - /bin/cp -Rf backend-gedure/* ../../laravel
    - /bin/rm -Rf ../../public_html/static
    - /bin/cp -Rf backend-gedure/public/* $DEPLOYPATH
    - cd ../../laravel
    - /opt/cpanel/composer/bin/composer install
